/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Keuangan.BAB4;

import Keuangan.BAB2.*;
import Keuangan.BAB1.*;
import Keuangan.BAB3.Transaksi;
import java.text.DecimalFormat;

/**
 *
 * @author brili
 */
public class GUI_Mutasi extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Nasabah
     */
    public GUI_Mutasi() {
        initComponents();{

    // Set Tanggal tidak bisa diedit
   txtBiayaAdmin.setEnabled(false);
}
        Mutasi_Rekening mutasi = new Mutasi_Rekening("", "", "", "", "", 0.0, 0.0, 0.0);
    txtBiayaAdmin.setText(String.valueOf(mutasi.getBiayaAdmin()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        norek = new javax.swing.JLabel();
        txtnorek = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        SaldoAwal = new javax.swing.JLabel();
        jenis_akun = new javax.swing.JLabel();
        SetoranAkhir = new javax.swing.JLabel();
        Limit = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        Penarikan = new javax.swing.JLabel();
        tglBuka = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        BiayaAdmin = new javax.swing.JLabel();
        txtBiayaAdmin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoMutasi = new javax.swing.JTextArea();
        btnCetak = new javax.swing.JButton();
        txtnama = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        txtSaldoAwal = new javax.swing.JTextField();
        txtSetoran = new javax.swing.JTextField();
        txtLimit = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        txtPenarikan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel1.setText("Bank Sekar Pradana ");

        norek.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        norek.setText("Nomor Rekening");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel3.setText("Data Nasabah ");

        nama.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        nama.setText("Nama Nasabah");

        SaldoAwal.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        SaldoAwal.setText("Saldo Awal");

        jenis_akun.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jenis_akun.setText("Jenis akun");

        SetoranAkhir.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        SetoranAkhir.setText("Setoran Akhir");

        Limit.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Limit.setText("Limit Transaksi");

        Status.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Status.setText("Status Akun");

        Penarikan.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Penarikan.setText("Penarikan Terakhir");

        tglBuka.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        tglBuka.setText("Tanggal Buka");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Non Aktif" }));

        BiayaAdmin.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        BiayaAdmin.setText("Biaya Admin");

        memoMutasi.setColumns(20);
        memoMutasi.setRows(5);
        jScrollPane1.setViewportView(memoMutasi);

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Keuangan/BAB4/icon.png"))); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaldoAwal)
                            .addComponent(SetoranAkhir)
                            .addComponent(Limit)
                            .addComponent(Status))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Penarikan)
                            .addComponent(tglBuka)
                            .addComponent(BiayaAdmin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBiayaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPenarikan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(norek)
                            .addComponent(nama)
                            .addComponent(jenis_akun))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnorek, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSaldoAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSetoran, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(norek)
                            .addComponent(txtnorek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCetak))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenis_akun)
                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaldoAwal)
                            .addComponent(txtSaldoAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SetoranAkhir)
                            .addComponent(txtSetoran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Limit)
                            .addComponent(txtLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Status)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tglBuka)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Penarikan)
                            .addComponent(txtPenarikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBiayaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BiayaAdmin))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
      String norek = txtnorek.getText();
      String nama = txtnama.getText();
      String jenisAkun = txtjenis.getText();
      String statusAkun = (String) cmbStatus.getSelectedItem();
      String tglBuka = txtTanggal.getText();

    double saldoAwal = Double.parseDouble(txtSaldoAwal.getText());
    double setoran = Double.parseDouble(txtSetoran.getText());
    double penarikan = Double.parseDouble(txtPenarikan.getText());

    // Membuat objek Mutasi_Rekening
    Mutasi_Rekening mutasi = new Mutasi_Rekening(norek, nama, jenisAkun, statusAkun, tglBuka,
    saldoAwal, setoran, penarikan);

    // Hitung saldo akhir
    double saldoAkhir = mutasi.hitungSaldoAkhir();

    // Tampilkan hasil ke TextArea
    DecimalFormat df = new DecimalFormat("#,##0.00");


    String saldoAwalFormatted = df.format(mutasi.getSaldoAwal());
    String setoranFormatted = df.format(mutasi.getSetoran());
    String penarikanFormatted = df.format(mutasi.getPenarikan());
    String saldoAkhirFormatted = df.format(saldoAkhir);
    String biayaAdminFormatted = df.format(mutasi.getBiayaAdmin());
    memoMutasi.setText(
            "\t\t Data Nasabah \n"+
            "\t Bank Sekar Pradana \n"+
            "No Rekening     \t: " + mutasi.getNoRekening() + "\n" +
            "Nama            \t: " + mutasi.getNama() + "\n" +
            "Jenis Akun      \t: " + mutasi.getJenisAkun() + "\n" +
            "Status Akun     \t: " + mutasi.getStatus() + "\n" +
            "Tanggal Buka    : " + mutasi.getTglBuka() + "\n\n" +
            
            "===== Mutasi Rekening =====\n" +
            "Saldo Awal      \t: Rp " + saldoAwalFormatted + "\n" +
            "Setoran         \t: Rp " + setoranFormatted + "\n" +
            "Penarikan       \t: Rp " + penarikanFormatted + "\n" +
            "Biaya Admin     \t: Rp " + mutasi.getBiayaAdmin() + "\n" +
            "Saldo Akhir     \t: Rp " + saldoAkhirFormatted+"\n"+
            "Terima Kasih" 
    );
    }//GEN-LAST:event_btnCetakActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Mutasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Mutasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Mutasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Mutasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Mutasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BiayaAdmin;
    private javax.swing.JLabel Limit;
    private javax.swing.JLabel Penarikan;
    private javax.swing.JLabel SaldoAwal;
    private javax.swing.JLabel SetoranAkhir;
    private javax.swing.JLabel Status;
    private javax.swing.JButton btnCetak;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenis_akun;
    private javax.swing.JTextArea memoMutasi;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel norek;
    private javax.swing.JLabel tglBuka;
    private javax.swing.JTextField txtBiayaAdmin;
    private javax.swing.JTextField txtLimit;
    private javax.swing.JTextField txtPenarikan;
    private javax.swing.JTextField txtSaldoAwal;
    private javax.swing.JTextField txtSetoran;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnorek;
    // End of variables declaration//GEN-END:variables
}
